# Generated by Django 4.2.2 on 2023-06-06 22:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pathlib


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=200, verbose_name='Имя файла')),
                ('filepath', models.FilePathField(null=True, path=pathlib.PurePosixPath('/home/marselle/Саморазвитие/Project/EDMS_IITU/media'), verbose_name='Путь к файлу')),
                ('date', models.DateField(verbose_name='Дата')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('signs_number', models.PositiveIntegerField(default=0, verbose_name='Количество подписей')),
                ('signed', models.PositiveIntegerField(default=0, verbose_name='Подписано')),
                ('status', models.CharField(default='В процессе', max_length=25, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Докменты',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notifications', models.TextField(blank=True, verbose_name='Уведомления')),
                ('approved', models.BooleanField(default=False, verbose_name='Одобрен')),
                ('files_to_review', models.ManyToManyField(blank=True, related_name='reviewer', to='web.document', verbose_name='Документы для рецензирования')),
                ('personal_files', models.ManyToManyField(blank=True, related_name='owner', to='web.document', verbose_name='Личные документы')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
        migrations.CreateModel(
            name='DiscussionText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200, verbose_name='Автор')),
                ('description', models.TextField(verbose_name='Описание')),
                ('publish_date', models.DateField(verbose_name='Дата публикации')),
                ('document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.document', verbose_name='Документ')),
            ],
            options={
                'verbose_name': 'Тема диалока',
                'verbose_name_plural': 'Темы диалока',
            },
        ),
    ]
