# Generated by Django 4.2.2 on 2023-06-06 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_remove_profile_files_to_contrib_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discussiontext',
            options={'verbose_name': 'Тема диалока', 'verbose_name_plural': 'Темы диалока'},
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': 'Документ', 'verbose_name_plural': 'Докменты'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
    ]
